name: whiteboard
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1
  firebase_core: ^0.4.0+6
  cloud_firestore: ^0.12.5+2
  firebase_auth: ^0.11.1+7
  modal_progress_hud: ^0.1.3
  intl: ^0.15.8
  carousel_slider: ^1.3.0
  toast: ^0.1.3
  shared_preferences: ^0.5.3+1
  file_picker: ^1.3.7
  firebase_storage: ^3.0.3
  http: ^0.12.0+2
  uuid: ^2.0.2
  webview_flutter: ^0.3.10
  url_launcher: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/